[package]
name = "david-lifespan"
version = "0.1.0"
edition = "2024"

[dependencies]
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.14.7" }
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
parse-size = "1.1.0"
nohash-hasher = "0.2.0"
dlv-list = "0.6.0"
byteorder = "1.5.0"
